Add compiler warnings
mongodb-js/kerberos pull request #158
Opened 2023-07-31 23:43 UTC by rzhao271

### Description

Adds some compiler warnings to binding.gyp to resolve downstream [BinSkim](https://github.com/microsoft/binskim) issues.

#### What is changing?

This PR adds some additional options to VCCLCompilerTool in binding.gyp, and fixes some type-casting compilation warnings that showed up as a result.

##### Is there new documentation needed for these changes?

No.

#### What is the motivation for this change?

VS Code got some BinSkim issues having to do with this library after starting to use it. The issues are:

- Warnings 4244 and 4267 aren't enabled (this PR handles that)
- Compiler control guard (CFG) isn't enabled (not sure if relevant to this project, so I didn't add the flags for now)
- Spectre mitigation isn't enabled (waiting on some upstream PRs to be merged first, since this requires an unreleased node-gyp flag to fix)

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [x] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2023-08-01 16:25 UTC, durran commented
Thanks @rzhao271 for submitting. I've created a JIRA ticket (NODE-5505) to track this. I think we've decided we want to be super safe and add an assertion in JS that the string lengths cannot exceed the newly cast ULONG sizes. As for your questions, CFG I don't think is relevant here but would be great to have a separate ticket filed for Spectre mitigation - I do think that could possibly be relevant here.

2023-08-01 17:31 UTC, rzhao271 commented
It turns out ULONG_MAX = 2^32 - 1, but the max string length that can be stored in V8 is currently under 2^29, ref https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length.

I also notice that the JS side within this repository doesn't seem to use all string fields with length casts. For example, `kerberos.initializeClient(service, initOptions, ...)` is never called with a `domain` option within this repository, but I assume a user could call into the `kerberos.initializeClient()` function from elsewhere and pass in a `domain` option.

Therefore, should string length checks be done on the C++ side instead?

2023-08-02 09:03 UTC, addaleax commented
> It turns out ULONG_MAX = 2^32 - 1, but the max string length that can be stored in V8 is currently under 2^29, ref https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length.

Yes – one option would be to add something that asserts that [`buffer.kStringMaxLength`](https://nodejs.org/api/buffer.html#bufferkstringmaxlength) is less than 2^32.

> Therefore, should string length checks be done on the C++ side instead?

If you want to add checks here, I think that would be more idiomatic, it just needs to happen in a bunch of places I guess.

2023-08-02 21:13 UTC, rzhao271 commented on src/win32/kerberos_win32.cc
> +    return str.size() >= ULONG_MAX;
I just noticed this field should be .length() to match the calls below, but let me know if the current change breaks styling guidelines. I wasn't sure whether to also put the throw statements in here.

2023-08-03 09:16 UTC, addaleax approved these changes, later dismissed

2023-08-03 09:16 UTC, addaleax commented on src/win32/kerberos_win32.cc
> +        return;
```suggestion
```

here and elsewhere, right? Otherwise this might end up generating compiler warnings about dead code.

2023-08-03 16:28 UTC, addaleax approved these changes, later dismissed

2023-08-07 13:17 UTC, durran approved these changes

2023-08-07 16:08 UTC, durran requested changes
@rzhao271 Looks good, thanks, with just some errors now on Windows:

```
[2023/08/07 14:53:16.337] c:\data\mci\292dae5a3c99d265424b7f58e8098eb2\src\src\win32\kerberos_win32.cc(131): error C2664: 'bool node_kerberos::isStringTooLong(const std::string &)': cannot convert argument 1 from 'std::wstring' to 'const std::string &' [C:\data\mci\292dae5a3c99d265424b7f58e8098eb2\src\build\kerberos.vcxproj]
[2023/08/07 14:53:16.337]   c:\data\mci\292dae5a3c99d265424b7f58e8098eb2\src\src\win32\kerberos_win32.cc(131): note: Reason: cannot convert from 'std::wstring' to 'const std::string'
[2023/08/07 14:53:16.337]   c:\data\mci\292dae5a3c99d265424b7f58e8098eb2\src\src\win32\kerberos_win32.cc(131): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
[2023/08/07 14:53:16.337] c:\data\mci\292dae5a3c99d265424b7f58e8098eb2\src\src\win32\kerberos_win32.cc(134): error C2664: 'bool node_kerberos::isStringTooLong(const std::string &)': cannot convert argument 1 from 'std::wstring' to 'const std::string &' [C:\data\mci\292dae5a3c99d265424b7f58e8098eb2\src\build\kerberos.vcxproj]
[2023/08/07 14:53:16.337]   c:\data\mci\292dae5a3c99d265424b7f58e8098eb2\src\src\win32\kerberos_win32.cc(134): note: Reason: cannot convert from 'std::wstring' to 'const std::string'
[2023/08/07 14:53:16.337]   c:\data\mci\292dae5a3c99d265424b7f58e8098eb2\src\src\win32\kerberos_win32.cc(134): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
[2023/08/07 14:53:16.337] c:\data\mci\292dae5a3c99d265424b7f58e8098eb2\src\src\win32\kerberos_win32.cc(137): error C2664: 'bool node_kerberos::isStringTooLong(const std::string &)': cannot convert argument 1 from 'std::wstring' to 'const std::string &' [C:\data\mci\292dae5a3c99d265424b7f58e8098eb2\src\build\kerberos.vcxproj]
[2023/08/07 14:53:16.337]   c:\data\mci\292dae5a3c99d265424b7f58e8098eb2\src\src\win32\kerberos_win32.cc(137): note: Reason: cannot convert from 'std::wstring' to 'const std::string'
[2023/08/07 14:53:16.337]   c:\data\mci\292dae5a3c99d265424b7f58e8098eb2\src\src\win32\kerberos_win32.cc(137): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

2023-08-08 00:27 UTC, durran commented
@rzhao271 thanks for the contribution and expedient responses. Much appreciated.

2023-08-08 00:28 UTC, merged