chore(NODE-6082): update dependencies
mongodb-js/kerberos pull request #171
Opened 2024-04-18 21:27 UTC by baileympearson

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2024-04-19 11:02 UTC, addaleax commented
See https://github.com/mongodb-js/kerberos/pull/172 for the CI failures here

2024-04-22 18:49 UTC, aditi-khare-mongoDB commented
Is there any reason we aren't updating the following dependency?
`node-gyp          ^10.0.1  →  ^10.1.0`

2024-04-22 18:50 UTC, aditi-khare-mongoDB requested changes
LGTM other than the one comment!

2024-04-22 20:20 UTC, aditi-khare-mongoDB approved these changes

2024-04-22 20:20 UTC, merged