feat(Node 6161): Sign Releases
mongodb-js/kerberos pull request #177
Opened 2024-06-07 21:35 UTC by aditi-khare-mongoDB

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Release Highlight

### Fill in title or leave empty for no highlight

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2024-06-20 15:42 UTC, nbbeeken commented on .github/docker/Dockerfile.glibc
> +RUN npm run install kerberos
Install kerberos lib according to debian instructions

2024-06-20 15:42 UTC, nbbeeken commented on .github/workflows/build.yml
> +        os: [macos-11, macos-latest, windows-2019]
remove macos-11

2024-06-20 15:43 UTC, nbbeeken commented on .github/workflows/build.yml
> +
npm install (check how we setup in FLE, we may also setup a nodejs version) somewhere here

2024-06-21 20:10 UTC, aditi-khare-mongoDB commented
https://github.com/mongodb-js/kerberos/actions/runs/9619228151
^^ example run with `npm publish` commmented out

2024-06-27 16:39 UTC, durran requested changes

2024-06-27 16:39 UTC, durran commented on README.md
> +No verification is done when using npm to install the package. To ensure release integrity when using npm, download the tarball manually from the GitHub release, verify the signature, then install th
```suggestion
No verification is done when using npm to install the package. To ensure release integrity when using npm, download the tarball manually from the GitHub release, verify the signature, then install the package from the downloaded tarball using npm install kerberos-X.Y.Z.tgz.
```

2024-06-27 19:19 UTC, baileympearson commented
duplicates https://github.com/mongodb-js/kerberos/pull/179

2024-06-27 19:19 UTC, closed without merging