deps
mongodb-js/kerberos pull request #192
Opened 2024-08-08 18:43 UTC by baileympearson

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Release Highlight

### Fill in title or leave empty for no highlight

### Double check the following

- [ ] Ran `npm run check:lint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2024-08-09 18:15 UTC, aditi-khare-mongoDB requested changes

2024-08-09 18:15 UTC, aditi-khare-mongoDB commented on package.json
Can we also add the following updates, or are they not desirable / cause issues?

```
@types/node     ^22.1.0  →  ^22.2.0
mocha           ^10.7.0  →  ^10.7.3
node-gyp        ^10.1.0  →  ^10.2.0
prebuild        ^13.0.0  →  ^13.0.1
```

2024-08-13 17:32 UTC, baileympearson commented on package.json
Done.  Also upgraded eslint, since a release came out since last week.

I also mentioned this in the PR description, but this PR doesn't update node-gyp and prebuild because our docker images don't have python3.10 installed, required for the new node-gyp version.

I did try and install python3.10 for a while in our dockerfile, but ran into issues. We're still on the current major version of node-gyp, we should be fine with this version for a while.

2024-08-15 15:07 UTC, aditi-khare-mongoDB approved these changes

2024-08-15 15:07 UTC, merged